rmdir /S /Q bin
rmdir /S /Q obj
rmdir /S /Q packages
rmdir /S /Q GridInQuestIINet/obj
rmdir /S /Q runtime.linux-arm.GridInQuestIINet/obj
rmdir /S /Q runtime.linux-x64.GridInQuestIINet/obj
rmdir /S /Q runtime.linux-x86.GridInQuestIINet/obj
rmdir /S /Q runtime.win-x64.GridInQuestIINet/obj
rmdir /S /Q runtime.win-x86.GridInQuestIINet/obj
